NewsPortal/NewsPortal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),  # Оставили только allauth
    path('', include('news.urls')),
]

NewsPortal/news/urls.py
from django.urls import path
from .views import (
    PostList, SearchPostList,
    NewsList, CreateNews, EditNews, DeleteNews, NewsDetail,
    ArticleList, ArticleDetail, CreateArticle, EditArticle, DeleteArticle,
    subscriptions,
)
urlpatterns = [
    path('', PostList.as_view(), name='home'),
    path('search/', SearchPostList.as_view(), name='search'),
    path('news/', NewsList.as_view(), name='news'),
    path('news/<int:pk>/', NewsDetail.as_view(), name='news_detail'),
    path('news/create/', CreateNews.as_view(), name='news_create'),
    path('news/<int:pk>/edit/', EditNews.as_view(), name='news_edit'),
    path('news/<int:pk>/delete/', DeleteNews.as_view(), name='news_delete'),
    path('articles/', ArticleList.as_view(), name='articles'),
    path('articles/<int:pk>/', ArticleDetail.as_view(), name='article_detail'),
    path('articles/create/', CreateArticle.as_view(), name='article_create'),
    path('articles/<int:pk>/edit/', EditArticle.as_view(), name='article_edit'),
    path('articles/<int:pk>/delete/', DeleteArticle.as_view(), name='article_delete'),
    path('subscriptions/', subscriptions, name='subscriptions'),
]

NewsPortal/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from datetime import datetime


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_rating = models.IntegerField(default=0)

    def update_rating(self):
        sum_rating = self.post_set.aggregate(post_rating=Sum('rating'))
        result_sum_rating = 0
        try:
            result_sum_rating += sum_rating.get('rating')
        except TypeError:
            result_sum_rating = 0

        sum_comment_rating = self.user.comment_set.aggregate(comment_rating=Sum('comment_rating'))
        result_sum_comment_rating = 0
        result_sum_comment_rating += sum_comment_rating.get('comment_rating')

        # суммарный рейтинг каждой статьи автора умноженный на 3
        self.user_rating = result_sum_rating * 3 + result_sum_comment_rating
        # сохраняем результаты в базу данных
        self.save()

    def __str__(self):
        return self.user.username


class Category(models.Model):
    category = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.category.title()


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    article = 'AR'
    news = 'NW'

    POSITIONS = [
        (article, 'Статья'),
        (news, 'Новость')
    ]
    position = models.CharField(max_length=2,
                                choices=POSITIONS,
                                default=article)
    date = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=255)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return (self.text[:124] + '...') if self.text else 'Текст не найден'

    def __str__(self):
        return f'{self.title}: {self.text}'

    def get_absolute_url(self):
        post = 'news' if self.position == 'NW' else 'articles'
        return 'http://127.0.0.1:8000/' + post + '/' + str(self.pk) + '/'



class PostCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    past = models.ForeignKey(Post, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author_of_comment = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)
    comment_rating = models.IntegerField(default=0)

    def like(self):
        self.comment_rating += 1
        self.save()

    def dislike(self):
        self.comment_rating -= 1
        self.save()


class Subscriber(models.Model):
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, related_name='subscribers')
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name='subscribers')

NewsPortal/templates/posts/Articles/article_create.html
{% extends 'flatpages/default.html' %}

{% block title %}
создание статьи
{% endblock title %}

{% block content %}
<h1>Создание Статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Создать"/>
</form>
{% endblock content %}

NewsPortal/templates/posts/Articles/article_delete.html
{% extends 'flatpages/default.html' %}


{% block title %}
Удаление {{ object.name }}
{% endblock title %}


{% block content %}
<h1>Удаление статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p> Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Удалить" />
</form>
{% endblock content %}

NewsPortal/templates/posts/Articles/article_detail.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}


{% block title %}
{{ article.title|censor }}
{% endblock title %}


{% block content %}
    <h1>{{ article.title|censor }}</h1>
    <p>{{ article.date|date:"d.m.Y" }}</p>
    <hr>
    <p>{{ article.text|censor }}</p>
    {% if perms.news.create_post %}
        <a href="{% url 'article_edit' article.id %}">Изменить</a>
    {% endif %}
    {% if perms.news.delete_post %}
        <a href="{% url 'article_delete' article.id %}">Удалить</a>
    {% endif %}
{% endblock content %}

NewsPortal/templates/posts/Articles/article_list.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
Статьи
{% endblock title %}

{% block content %}
    <h1>Статьи</h1>
    <hr>
        {% if perms.news.add_post %}
            <a href="{% url 'article_create' %}">Добавить статью</a>
        {% endif %}

    {% if articles %}
        <table>
            <tr>
                <td> Заголовок </td>
                <td> Дата публикации </td>
                <td> Текст статьи </td>
                {% if perms.news.change_post or perms.news.delete_post %}
                    <td> Действия </td>
                {% endif %}
            </tr>
            {% for post in articles %}
                <tr>
                    <td>{{ post.title|censor }}</td>
                    <td>{{ post.date|date:'M d Y' }}</td>
                    <td>{{ post.text|truncatechars:20|censor }}</td>
                    <td>
                        {% if perms.news.change_post %}
                            <a href="{% url 'article_edit' post.id %}">Изменить</a>
                        {% endif %}
                        {% if perms.news.delete_post %}
                            <a href="{% url 'article_delete' post.id %}">Удалить</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>статей нету!</h2>
    {% endif %}

       {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}